#!/usr/bin/env python3

import sys
import socket
import subprocess
import argparse
import pathlib
import configparser
import os

parser = argparse.ArgumentParser()
parser.add_argument("hostname", help="hostname to connect to")
parser.add_argument("-c", "--console", help="connect to console",
                    action="store_true")
parser.add_argument("-a", "--admin", help="use admin account",
                    action="store_true")
parser.add_argument("-v", "--vmname", help="enter vm name on host to connect",
                    type=str)
parser.add_argument("-f", "--fullscreen", 
                    help="enter session in fullscreen mode", action="store_true")
parser.add_argument("-u", "--username", help="enter a custom username",
                    type=str)
parser.add_argument("-s", "--shortcut",
                    help="enter shortcut name", action="store_true")
parser.add_argument("-r", "--redirection",
                    help="Enable home drive redirection",
                    action="store_true")
parser.add_argument("-d", "--debug", help="enable debug output", action="store_true")
args = parser.parse_args()

config = configparser.ConfigParser()
home = pathlib.Path(os.environ['HOME'])
cDir = home.joinpath('.ts')
cFile = cDir.joinpath('ts.ini')
config.read(str(cFile))
if not config.sections():
    sys.exit("Failed to read config")

user = config[config['DEFAULT']['user']]

if args.shortcut:
    shortcut = (config['shortcuts'][args.hostname]).split(';')
    hostname = shortcut[0]
    if len(shortcut) > 1:
        args.vmname = shortcut[1]
    if len(shortcut) == 3:
        user = config[shortcut[2]]
else:
    hostname = args.hostname

if args.admin:
    user = config[config['DEFAULT']['admin']]
else:
    if args.username:
        user = config[args.username]

username = user['domain'] + '\\' + user['username']
pw = user['password']

if args.vmname:
    vmpath = pathlib.Path("/home/harrisj/.ts/{}/{}".format(hostname,
                          args.vmname))
    if vmpath.is_file():
        print("Reading file {}".format(str(vmpath)))
        with open(str(vmpath), 'r') as vmguidfile:
            vmguid = vmguidfile.read().replace('\n', '')
    else:
        sys.exit("Wrong VM Name or no Guid file")

if '.' in str(hostname):
    hostname = str(hostname)
else:
    hostname = str(hostname) + ".usc.internal"

ip = socket.gethostbyname(hostname)
cmdargs = ["xfreerdp", "/v:{}".format(ip), "/cert-tofu", "/cert-ignore",  
        "/u:{}".format(username), "/p:{}".format(pw),
        "/dynamic-resolution"]
if args.console:
    cmdargs.append("/admin")
if args.vmname:
    cmdargs.append("/vmconnect:{}".format(str(vmguid)))
if args.fullscreen:
    # Attempt to get almost fullscreen by getting current resolution
    xrandrOut = subprocess.check_output(["xrandr"])
    lookforconnected = False
    for line in xrandrOut.splitlines():
        line = str(line)
        if " connected " in line:
            if "disconnected" in line:
                lookforconnected = True
            else:
                res = line.split(" ")[2].split('+')[0]
                x = res.split('x')[0]
                y = res.split('x')[1]
        if lookforconnected:
            if " connected " in line:
                res = line.split(" ")[2].split('+')[0]
                x = res.split('x')[0]
                y = res.split('x')[1]


    if x and y:
        cmdargs.append("/h:{}".format(int(y) - 70))
        cmdargs.append("/w:{}".format(int(x)))
    else:
        cmdargs.append("/f")

if args.redirection:
    cmdargs.append("/drive:auto,*")
    cmdargs.append("/drive:home,/home/harrisj")

if args.debug:
    print("Executing {}".format(cmdargs))
    result = subprocess.Popen(cmdargs)
else:
    result = subprocess.Popen(cmdargs, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL)

