#!/usr/bin/env python3

import sys
import socket
import subprocess
import argparse
import pathlib
import configparser
import os
import json
import getpass
import gnupg

parser = argparse.ArgumentParser()
parser.add_argument("hostname", help="hostname to connect to")
parser.add_argument("-c", "--console", help="connect to console",
                    action="store_true")
parser.add_argument("-x", "--scale", help="scale",
                    action="store_true")
parser.add_argument("-a", "--admin", help="use admin account",
                    action="store_true")
parser.add_argument("-v", "--vmname", help="enter vm name on host to connect",
                    type=str)
parser.add_argument("-f", "--fullscreen", 
                    help="enter session in fullscreen mode", action="store_true")
parser.add_argument("-u", "--username", help="enter a custom username",
                    type=str)
parser.add_argument("-s", "--shortcut",
                    help="enter shortcut name", action="store_true")
parser.add_argument("-r", "--redirection",
                    help="Enable home drive redirection",
                    action="store_true")
parser.add_argument("-p", "--password-backend", choices=['1password', 'tsini', 'gpg'])
parser.add_argument("--snd",
                    help="Pass sound devices", action="store_true")
parser.add_argument("-d", "--debug", help="enable debug output", action="store_true")
args = parser.parse_args()

config = configparser.ConfigParser()
home = pathlib.Path(os.environ['HOME'])
cDir = home.joinpath('.ts')
cFile = cDir.joinpath('ts.ini')
config.read(str(cFile))
if not config.sections():
    sys.exit("Failed to read config")

if not args.password_backend:
    try:
        backend = config['DEFAULT']['backend']
    except:
        print("No password backend configured in ini. Using tsini")
        backend = 'tsini'

user = config[config['DEFAULT']['user']]

if args.shortcut:
    shortcut = (config['shortcuts'][args.hostname]).split(';')
    hostname = shortcut[0]
    if len(shortcut) > 1:
        args.vmname = shortcut[1]
    if len(shortcut) == 3:
        user = config[shortcut[2]]
else:
    hostname = args.hostname

if args.admin:
    user = config[config['DEFAULT']['admin']]
else:
    if args.username:
        user = config[args.username]

username = user['domain'] + '\\' + user['username']
pw = None
if backend == 'gpg':
    gpg = gnupg.GPG(gnupghome=str(home.joinpath('.gnupg')))
    passstorepath = home.joinpath('.password-store/work')
    if user['domain'] == '':
        passfiledomainpath = passstorepath.joinpath('ts')
        passfilepath = passfiledomainpath.joinpath(user.name)
    else:
        passfiledomainpath = passstorepath.joinpath(user['domain'])
        passfilepath = passfiledomainpath.joinpath(user['username'])
    try:
        passfile = open(str(passfilepath) + '.gpg', "rb")
        pw = str(gpg.decrypt_file(passfile)).partition('\n')[0]
    except:
        print("file not found in gpg store")
elif backend == '1password':
    cmdargs = ["op", "get", "item", "--vault", "Personal", user['username']]
    pwproc = subprocess.Popen(cmdargs, stdout=subprocess.PIPE)
    pwout = pwproc.stdout.read()
    pwjson = json.loads(pwout)

    for field in pwjson['details']['sections'][0]['fields']:
        if field['n'] == 'password':
            pw = field['v']
else:
    pw = user['password']

if pw == None:
    pw = user['password']
if pw == None:
    pw = getpass.getpass(prompt='Password: ')

if args.vmname:
    vmpath = pathlib.Path("/home/harrisj/.ts/{}/{}".format(hostname,
                          args.vmname))
    if vmpath.is_file():
        print("Reading file {}".format(str(vmpath)))
        with open(str(vmpath), 'r') as vmguidfile:
            vmguid = vmguidfile.read().replace('\n', '')
    else:
        sys.exit("Wrong VM Name or no Guid file")

if '.' in str(hostname):
    hostname = str(hostname)
else:
    hostname = str(hostname) + ".usc.internal"

ip = socket.gethostbyname(hostname)
cmdargs = ["xfreerdp", "/v:{}".format(ip), "/cert-tofu", "/cert-ignore",  
        "/u:{}".format(username), "/p:{}".format(pw),
        "/dynamic-resolution", "/title:{}".format(hostname),
        "/wm-class:ts"]
if args.snd:
    cmdargs.append("/sound")
    cmdargs.append("/microphone")
if args.console:
    cmdargs.append("/admin")
if args.vmname:
    cmdargs.append("/vmconnect:{}".format(str(vmguid)))
if args.fullscreen:
    cmdargs.append("/multimon")

if args.scale:
    cmdargs.append("/scale:180")

if args.redirection:
    cmdargs.append("/drive:auto,*")
    cmdargs.append("/drive:home,/home/harrisj")

if args.debug:
    print("Executing {}".format(cmdargs))
    result = subprocess.Popen(cmdargs)
else:
    result = subprocess.Popen(cmdargs, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL)

