#!/usr/bin/env python3

import geoip2.database
import argparse
import re
import socket

parser = argparse.ArgumentParser()
parser.add_argument("ip", help="IP Address to get location for")

args = parser.parse_args()

reader = geoip2.database.Reader('/usr/share/GeoIP/GeoLite2-City.mmdb')
if re.match('^\w+',args.ip):
    ip = socket.gethostbyname(args.ip)
else:
    ip = args.ip

response = reader.city(ip)
location = ip + ": " + response.country.name
if response.subdivisions.most_specific.name:
    location += (", " + response.subdivisions.most_specific.name )
if response.city.name:
    location += (", " + response.city.name)

print(location)
